#!/usr/bin/Rscript

## This R script takes a BAM file generated by minimap2 alignment of long reads and convert it to a user-friendly summary table for downstream analysis

## USAGE: Load required R version `module load R/4.2` 
## USAGE: Run script on a BAM file `Rscript summarize_minimap2_alignment.r <indexed_bam_file_name> <output_file_prefix>`

## Make this script executable using `chmod +x summarize_minimap2_alignment.r` to run it from local directory

