## Parse the output file generated by <samtools stats>
ParseSamtoolStats <- function(fstat) {
  
  ## Read in all lines from stats file
  lns <- readLines(fstat);
  
  ###############################################################################################################
  grep_key <- function(key, lns) {
    grp <- sub(paste0(key, '\t'), '', lns[grep(key, lns)]);
    grp <- sub('\t#.+$', '', grp);
    grp;
  }
  calc_qual <- function(grp) {
    if (length(grp) > 0) {
      grp <- sub('^[0-9]+\t', '', grp);
      mtx <- do.call('rbind', strsplit(grp, '\t'));
      mtx <- apply(mtx, 2, as.numeric);
      ttl <- sapply(1:ncol(mtx), function(i) (i-1)*mtx[, i]);
      
      cbind(base_cycle=1:nrow(mtx), read_count=rowSums(mtx), mean_qual=rowSums(ttl)/rowSums(mtx));
    } else grp;
  }
  calc_gc <- function(grp) {
    if (length(grp) > 0) {
      pct <- as.numeric(sub('\t.+$', '', grp));
      cnt <- as.numeric(sub('^.+\t', '', grp));
      cbind(percent=pct, count=cnt);      
    } else grp;
  }
  ###############################################################################################################
  
  ## Output list
  out <- list();
  
  ## Summary Numbers
  grp <- grep_key("^SN", lns); 
  out$`Summary Numbers` <- as.numeric(sub('^.+\t', '', grp));
  names(out$`Summary Numbers`) <- sub(':\t.+$', '', grp);
  
  ## First Fragment Qualities
  grp <- grep_key("^FFQ", lns); 
  out$`First Fragment Qualities` <- calc_qual(grp);

  ## Last Fragment Qualities
  grp <- grep_key("^LFQ", lns); 
  out$`Last Fragment Qualities` <- calc_qual(grp);
  
  ## GC Content of first fragments
  grp <- grep_key("^GCF", lns); 
  out$`GC Content of first fragments` <- calc_gc(grp);
  
  ## GC Content of last fragments
  grp <- grep_key("^GCL", lns); 
  out$`GC Content of last fragments` <- calc_gc(grp);
  
  ## ACGT content per cycle
  grp <- grep_key("^GCC", lns); 
  grp <- do.call('rbind', strsplit(grp, '\t'));
  grp <- grp[, -1];
  grp <- apply(grp, 2, as.numeric);
  rownames(grp) <- 1:nrow(grp); 
  colnames(grp) <- c('A', 'C', 'G', 'T', 'N', 'O')[1:ncol(grp)];
  out$`ACGT content per cycle` <- grp;
  
  ## Insert sizes
  grp <- grep_key("^IS", lns);
  if (length(grp) > 0) {
    grp <- do.call('rbind', strsplit(grp, '\t'));
    grp <- apply(grp, 2, as.integer);
    colnames(grp) <- c("insert size", "pairs total", "inward oriented pairs", "outward oriented pairs", "other pairs");
  }
  out$`Insert sizes` <- grp;
  
  ## Read lengths
  grp <- grep_key("^RL", lns);
  grp <- cbind(read_length=as.integer(sub('\t.+$', '', grp)), read_count=as.integer(sub('^.+\t', '', grp)));
  out$`Read lengths` <- grp;
  
  ## Indel distribution
  grp <- grep_key("^ID", lns);
  grp <- do.call('rbind', strsplit(grp, '\t'));
  grp <- apply(grp, 2, as.integer);
  colnames(grp) <- c('length', 'num_insertion', 'num_deletion');
  out$`Indel distribution` <- grp;
  
  ## Indels per cycle
  grp <- grep_key("^IC", lns);
  grp <- do.call('rbind', strsplit(grp, '\t'));
  grp <- apply(grp, 2, as.integer);
  colnames(grp) <- c('base_cycle', 'num_insertion_fwd', 'num_insertion_rev', 'num_deletion_fwd', 'num_deletion_rev');
  
  out;
}